docker/johnsnowlabs_fastapi/Dockerfile, docker/johnsnowlabs_fastapi/README.md, docker/johnsnowlabs_fastapi/docker-compose.yaml, docker/johnsnowlabs_fastapi/fastapi_app.py, docker/johnsnowlabs_fastapi/license.json
This PR aims to add all the necessary files to run johnsnowlabs library inside a Docker container with FastAPI.
=> Adds a johnsnowlabs Docker image files with FastAPI

johnsnowlabs/settings.py, johnsnowlabs/utils/my_jsl_api.py
- Bump NLU version 
- Update client ID to dedicated jsl-lib secret for OAUTH
=> 4.3.2 release

johnsnowlabs/settings.py
- fix bug that caused failure when installing enterprise-nlp 4.3.2
=> John Snow Labs 4.3.5 Library Release

docs/_layouts/redirect.html, docs/_plugins/search_index.rb
Jira Ticket [NMH-173](https://johnsnowlabs.atlassian.net/browse/NMH-173)
=> NMH-173: Remove content noindex directive

docs/_posts/bunyamin-polat/2023-04-13-finner_sec_edgar_en.md, docs/_posts/gadde5300/2023-04-05-finsum_flant5_base_en.md, docs/_posts/gadde5300/2023-04-13-finsum_flant5_finetuned_sec10k_en.md
=> Finance NLP 1.11.0

docs/_includes/demomenu.html, docs/demos/medical_question_answering.md, docs/demos/medical_text_generation.md, docs/demos/medical_text_summarization.md
=> Update Biomedical NLP

johnsnowlabs/utils/env_utils.py, johnsnowlabs/utils/venv_utils.py
quick fix to a problem using type hinting: `list[str]` instead of:
```python
from typing import List
func(param: List[str]):
return
```
=> Fix type hinting

docs/_posts/Cabir40/2023-03-29-oncology_biomarker_pipeline_en.md, docs/_posts/Cabir40/2023-03-29-oncology_diagnosis_pipeline_en.md, docs/_posts/Cabir40/2023-03-29-oncology_general_pipeline_en.md, docs/_posts/Cabir40/2023-03-29-oncology_therapy_pipeline_en.md, docs/_posts/Cabir40/2023-03-30-summarizer_generic_jsl_en.md, docs/_posts/Cabir40/2023-04-03-summarizer_biomedical_pubmed_en.md, docs/_posts/Cabir40/2023-04-03-summarizer_clinical_questions_en.md, docs/_posts/Cabir40/2023-04-03-text_generator_biomedical_biogpt_base_en.md, docs/_posts/Cabir40/2023-04-03-text_generator_generic_flan_base_en.md, docs/_posts/Cabir40/2023-04-03-text_generator_generic_jsl_base_en.md, docs/_posts/Cabir40/2023-04-12-biogpt_chat_jsl_en.md, docs/_posts/Damla-Gurbaz/2023-01-14-genericclassifier_sdoh_alcohol_usage_sbiobert_cased_mli_en.md, docs/_posts/Damla-Gurbaz/2023-01-14-genericclassifier_sdoh_tobacco_usage_sbiobert_cased_mli_en.md, docs/_posts/HashamUlHaq/2023-03-25-summarizer_clinical_jsl.md, docs/_posts/HashamUlHaq/2023-03-25-summarizer_clinical_jsl_en.md, docs/_posts/HashamUlHaq/2023-03-30-summarizer_clinical_jsl_augmented_en.md, docs/_posts/HashamUlHaq/2023-04-04-text_generator_generic_flan_t5_large_en.md, docs/_posts/Meryem1425/2023-02-10-ner_sdoh_demographics_wip_en.md, docs/_posts/Meryem1425/2023-02-10-ner_sdoh_income_social_status_wip_en.md, docs/_posts/Meryem1425/2023-02-10-ner_sdoh_social_environment_wip_en.md, docs/_posts/Meryem1425/2023-02-11-ner_sdoh_wip_en.md, docs/_posts/Meryem1425/2023-02-25-ner_vop_slim_wip_en.md, docs/_posts/gokhanturer/2023-04-12-ner_deid_large_emb_clinical_large_en.md, docs/_posts/gokhanturer/2023-04-12-ner_deid_large_emb_clinical_medium_en.md, docs/_posts/gokhanturer/2023-04-12-ner_posology_emb_clinical_large_en.md, docs/_posts/gokhanturer/2023-04-12-ner_posology_emb_clinical_medium_en.md, docs/_posts/mauro-nievoff/2023-03-30-ner_vop_wip_en.md, docs/_posts/mauro-nievoff/2023-04-12-ner_vop_emb_clinical_large_wip_en.md, docs/_posts/mauro-nievoff/2023-04-12-ner_vop_emb_clinical_medium_wip_en.md
📌 Related demo/colab link has been added to md files with missing demo/colab link.
=> Updated md files

docs/_posts/Damla-Gurbaz/2023-05-01-bert_token_classifier_ner_jsl_en.md
[bert_token_classifier_ner_jsl](https://nlp.johnsnowlabs.com/2022/03/21/bert_token_classifier_ner_jsl_en_2_4.html) model has been retrained with ner_jsl data.
=> 2023-05-01-bert_token_classifier_ner_jsl_en

docs/_posts/Meryem1425/2023-04-28-icd10cm_resolver_pipeline_en.md
update pipeline for chunk2doc component
=> 2023-04-28-icd10cm_resolver_pipeline_en

docs/_posts/Cabir40/2023-04-28-ner_profiling_biobert_en.md, docs/_posts/Cabir40/2023-04-28-ner_profiling_clinical_en.md
We have updated `ner_profiling_clinical` and `ner_profiling_biobert`
and we uploaded both pyspark version 3.0 and 3.2
=> 2023-04-28-ner_profiling_biobert_en

docs/_posts/Ahmetemintek/2023-02-23-rxnorm_nih_mapper_en.md, docs/_posts/HashamUlHaq/2022-10-25-t5_base_pubmedqa_en.md, docs/_posts/hsaglamlar/2023-04-10-genericclassifier_sdoh_mental_health_clinical_en.md, docs/_posts/mauro-nievoff/2023-03-30-ner_vop_wip_en.md, docs/_posts/mauro-nievoff/2023-04-12-ner_vop_emb_clinical_large_wip_en.md, docs/_posts/mauro-nievoff/2023-04-12-ner_vop_emb_clinical_medium_wip_en.md
Jira Ticket [NMH-171](https://johnsnowlabs.atlassian.net/browse/NMH-171)
=> BUGFIX NMH-171: Fix multiselect for existing licensed docs [skip-test]

docs/_posts/Cabir40/2023-05-04-bert_token_classifier_ner_jsl_en.md, docs/_posts/Cabir40/2023-05-04-ner_profiling_clinical_en.md
ner_profiling_clinical => updated for pyspark v3.3.1
bert_token_classifier_ner_jsl => updated for tensorflow files
=> 2023-05-04-ner_profiling_clinical_en

docs/_posts/bunyamin-polat/2023-05-14-finner_responsibility_reports_md_en.md
* Add model 2023-05-14-finner_responsibility_reports_md_en
* Update 2023-05-14-finner_responsibility_reports_md_en.md
---------
=> Finance NLP 1.13.0

docs/_posts/Cabir40/2023-05-15-biogpt_pubmed_qa_en.md, docs/_posts/Cabir40/2023-05-15-flan_t5_base_jsl_qa_en.md
added two new model that compatible with v4.4.2
=> 2023-05-15-biogpt_pubmed_qa_en

docs/en/spark_nlp_healthcare_versions/licensed_release_notes.md, docs/en/spark_nlp_healthcare_versions/release_notes_4_4_2.md
=> update release notes

docs/en/licensed_install.md
updated windows installation setup
=> Window installation setup

docs/_includes/docs-healthcare-pagination.html, docs/en/spark_nlp_healthcare_versions/release_notes_4_4_3.md
Added New 4.4.3 Release Notes to Web Page
=> 4.4.3 Release Notes

docs/en/spark_nlp_healthcare_versions/licensed_release_notes.md, docs/en/spark_nlp_healthcare_versions/release_notes_4_4_2.md, docs/en/spark_nlp_healthcare_versions/release_notes_4_4_3.md
✔︎ Updated model pages links in release_notes_44.3 and 4.4.2
=> Updated release notes

docs/_posts/Cabir40/2023-06-08-ner_demographic_extended_healthcare_en.md
added new model with @andrei9825
=> 2023-06-08-ner_demographic_extended_healthcare_en

johnsnowlabs/py_models/jsl_secrets.py, johnsnowlabs/utils/my_jsl_api.py, tests/install.py, tests/jsl_secrets.py
Jira Ticket [MYJSL-369](https://johnsnowlabs.atlassian.net/browse/MYJSL-369)
=> FEATURE MYJSL-369: Use compatabile secrets to install

docs/_posts/mellahysf/2023-08-14-text2sql_mimicsql_en.md
=> updated description

docs/en/ocr_pipeline_components.md
Hey @albertoandreottiATgmail ,
1. Keeping _autosummary
2. Gemfile.lock did not change.
3. Update ocr_pipeline_components.md for ImageDrawRegions & DicomDrawRegions
=> OCR_PipelineComponents_Update

johnsnowlabs/auto_install/emr/install_utils.py
-Add hadoop user to hdfs admin group
=> Update EMR initialization script

docker/johnsnowlabs_fastapi/fastapi_app.py
=> fastapi_api.py updated

docs/_includes/docs-sparckocr-pagination.html, docs/en/spark_ocr_versions/release_notes_5_0_2.md, docs/en/version_compatibility.md
- Updated Visual NLP Release Notes Related Parts
=> Visual NLP Release Notes

docs/en/jsl/jsl_release_notes.md, johnsnowlabs/settings.py
- enterprise nlp to 5.1.2
- open source nlp to 5.1.2
- nlu to 5.0.4rc2
=> bump version and docs

docs/_posts/C-K-Loan/2023-06-17-ner_biomarker_pipeline_en.md, docs/_posts/C-K-Loan/2023-06-17-oncology_general_pipeline_en.md, docs/_posts/C-K-Loan/2023-06-17-oncology_therapy_pipeline_en.md, docs/_posts/Cabir40/2023-06-16-oncology_general_pipeline_en.md, docs/_posts/ahmedlone127/2023-06-16-oncology_general_pipeline_en.md, docs/en/spark_nlp_healthcare_versions/licensed_release_notes.md, docs/en/spark_nlp_healthcare_versions/release_notes_5_1_2.md
1.The LANGTESTNER example and result in the 5.1.2 release note have been removed.
2. Fixed MD cards coming as issues
=> md files and release note updated

docs/en/licensed_annotator_entries/DeIdentification.md, docs/en/licensed_annotator_entries/MedicalBertForSequenceClassification.md, docs/en/licensed_annotator_entries/MedicalBertForTokenClassifier.md, docs/en/licensed_annotator_entries/MedicalDistilBertForSequenceClassification.md
Added new Annotator docs information
Updated Deidentification doc information
=> annotator doc update

docs/en/licensed_annotator_entries/AnnotationMerger.md, docs/en/licensed_annotator_entries/MedicalBertForTokenClassifier.md
fixed typos on MedicalBertForTokenClassification
fixed finance and legal code examples on AnnotatorionMerger
=> fixed typos

docs/en/licensed_annotator_entries/AnnotationMerger.md, docs/en/licensed_annotator_entries/AssertionChunkConverter.md, docs/en/licensed_annotators.md
- Updated AssertionChunkConverter md file 
-added finance and legal python and scala code and update medical code
=> AssertionChunkConverter annotator is updated

docs/en/licensed_install.md
added docker image installation instructions
updated some versions
=> update docker installation instructions

johnsnowlabs/utils/sparksession_utils.py
warmup imports for install checks. fixes bugs where jsl fails to detect installed libraries. particular in DB environments
=> warmup imports for install checks

docs/en/licensed_annotator_entries/RENerChunksFilter.md, docs/en/licensed_annotator_entries/ReIdentification.md, docs/en/licensed_annotator_entries/RelationExtraction.md, docs/en/licensed_annotator_entries/RelationExtractionDL.md, docs/en/licensed_annotator_entries/Summarizer.md, docs/en/licensed_annotator_entries/TFGraphBuilder.md, docs/en/licensed_annotator_entries/TextGenerator.md, docs/en/licensed_annotator_entries/ZeroShotNerModel.md, docs/en/licensed_annotator_entries/ZeroShotRelationExtraction.md
Updated the md files of the following annotators:
- RENerChunksFilter
- ReIdentification
- RelationExtractionDL
- Summarizer
- TFGraphBuilder
- TextGenerator
- ZeroShotNerModel
- ZeroShotRelationExtraction
=> Update annotators md files

johnsnowlabs/finance.py, johnsnowlabs/legal.py, johnsnowlabs/medical.py
issue --> https://github.com/JohnSnowLabs/johnsnowlabs/issues/798
- InternalDocumentSplitter
=> Addition to InternalDocumentSplitter

johnsnowlabs/finance.py, johnsnowlabs/frameworks/embedding_retrieval/haystack_node.py, johnsnowlabs/legal.py, johnsnowlabs/medical.py, johnsnowlabs/settings.py
- https://github.com/JohnSnowLabs/johnsnowlabs/pull/789 
-  https://github.com/JohnSnowLabs/johnsnowlabs/pull/802 
- https://github.com/JohnSnowLabs/johnsnowlabs/pull/799
- bump visual to 510
- bump medical to 514
=> Release/ 519

docs/_posts/2020-09-23-assertion_dl_healthcare_en.md, docs/en/licensed_annotator_entries/DocumentMLClassifier.md, docs/en/licensed_annotator_entries/FewShotClassifier.md, docs/en/licensed_annotator_entries/InternalDocumentSplitter.md, docs/en/licensed_annotator_entries/NerQuestionGenerator.md, docs/en/licensed_annotator_entries/Replacer.md, docs/en/licensed_annotator_entries/ResolverMerger.md, docs/en/licensed_annotator_entries/Router.md
Added new annotator MD files:
- DocumentMLClassifier
- FewShotClassifier
- InternalDocumentSplitter
- NerQuestionGenerator
- Replacer
- ResolverMerger
- Router
Updated https://nlp.johnsnowlabs.com/2020/09/23/assertion_dl_healthcare_en.html this md file too.
=> Added new annotator

docs/en/licensed_annotator_entries/QuestionAnswering.md, docs/en/licensed_annotator_entries/RENerChunksFilter.md, docs/en/licensed_annotator_entries/ReIdentification.md, docs/en/licensed_annotator_entries/RelationExtractionDL.md, docs/en/licensed_annotator_entries/Summarizer.md, docs/en/licensed_annotator_entries/TFGraphBuilder.md, docs/en/licensed_annotator_entries/TextGenerator.md, docs/en/licensed_annotator_entries/ZeroShotNerModel.md, docs/en/licensed_annotator_entries/ZeroShotRelationExtraction.md
updated QuestionAnsweribg and ReIdentification
fixed some typos
=> Updated annotators md files

docs/_posts/aymanechilah/2023-11-06-image_handwritten_transformer_extraction_en_3_2.md
updated md file with this timestamp ..5.0.2_3.0_1699469925000.zip
=> updated missing link

docs/en/licensed_annotator_entries/GenericSVMClassifier.md
annotater-updated: GenericSVMClassifier added
=> annotater-updated

docs/en/licensed_annotator_entries/ContextualParser.md, docs/en/licensed_annotator_entries/GenericSVMClassifier.md, docs/en/licensed_annotator_entries/IOBTagger.md, docs/en/licensed_annotator_entries/MedicalBertForSequenceClassification.md, docs/en/licensed_annotator_entries/MedicalBertForTokenClassifier.md, docs/en/licensed_annotator_entries/MedicalDistilBertForSequenceClassification.md
Updated:
- IOBTagger
- ContextualParser
- GenericSVMClassifier
- MedicalBertForSequenceClassification
- MedicalBertForTokenClassifier
- MedicalDistilBertForSequenceClassification
=> updated annotator

docs/en/alab/install.md
Changed storage requirement in the installation page for NLP lab
=> Changed storage requirement in the installation page for NLP lab

docs/_posts/akrztrk/2023-12-20-bert_sequence_classifier_sdoh_frailty_vulnerability_en.md, docs/_posts/akrztrk/2023-12-20-bert_sequence_classifier_sdoh_mental_health_en.md, docs/_posts/akrztrk/2023-12-20-bert_sequence_classifier_sdoh_violence_abuse_en.md
Three new models have been added: 
"bert_sequence_classifier_sdoh_mental_health" model for Mental Health,
"bert_sequence_classifier_sdoh_violence_abuse" model for Violence and Abuse,  "bert_sequence_classifier_sdoh_frailty_vulnerability" model for Frailty and Vulnerability.
=> 2023-12-20-bert_sequence_classifier_sdoh_mental_health_en

docs/_posts/akrztrk/2023-12-20-bert_sequence_classifier_sdoh_frailty_vulnerability_en.md, docs/_posts/akrztrk/2023-12-20-bert_sequence_classifier_sdoh_mental_health_en.md, docs/_posts/akrztrk/2023-12-20-bert_sequence_classifier_sdoh_violence_abuse_en.md, docs/_posts/akrztrk/2023-12-21-bert_sequence_classifier_clinical_sections_en.md, docs/_posts/akrztrk/2023-12-21-bert_sequence_classifier_clinical_sections_headless_en.md
added new 2 section header classification models and 3 new SDOH models
=> Models hub internal to Main

docs/_posts/C-K-Loan/2023-06-17-explain_clinical_doc_medication_en.md, docs/_posts/C-K-Loan/2023-06-17-re_bodypart_proceduretest_pipeline_en.md, docs/_posts/Cabir40/2023-04-03-summarizer_biomedical_pubmed_en.md, docs/_posts/Cabir40/2023-04-03-summarizer_clinical_questions_en.md, docs/_posts/Cabir40/2023-08-16-summarizer_clinical_laymen_onnx_en.md, docs/_posts/Meryem1425/2023-05-31-summarizer_clinical_laymen_en.md, docs/_posts/ahmedlone127/2023-06-13-re_test_result_date_pipeline_en.md, docs/_posts/ahmedlone127/2023-06-22-icd10cm_resolver_pipeline_en.md, docs/_posts/mauro-nievoff/2022-12-01-oncology_therapy_pipeline_en.md, docs/_posts/murat-gunay/2020-09-01-posology_re.md
Fixed some errors found in the MD cards.
=> updated md cards

docs/en/licensed_annotator_entries/AnnotationMerger.md, docs/en/licensed_annotator_entries/NameChunkObfuscator.md
The notebook link for the AnnotationMerger MD card has been corrected.
=> updated annotators

johnsnowlabs/finance.py, johnsnowlabs/legal.py, johnsnowlabs/medical.py
issue --> https://github.com/JohnSnowLabs/johnsnowlabs/issues/798
Added DocumentFiltererByClassifier to medical, finance, legal
Fixed ZeroShotNerModel imports because it was formerly used ZeroShotNerModel annotator in spark-nlp, not licensed ones
We need to merge this PR before 521
=> Addition DocumentFiltererByClassifier & Bugfix ZeroShotNer imports

docs/_posts/Cabir40/2024-01-22-sbiobert_base_cased_mli_onnx_en.md
Added new onnx version of sbiobert_base_cased_mli embeddings
=> 2024-01-22-sbiobert_base_cased_mli_onnx_en

docs/_posts/gpirge/2024-01-24-sbiobertresolve_snomed_findings_en.md
updated "sbiobertresolve_snomed_findings" md card.
=> updated md cart

docs/_posts/HashamUlHaq/2021-04-01-ner_ade_clinical_en.md, docs/_posts/ahmedlone127/2023-06-16-rxnorm_mesh_mapping_en.md, docs/_posts/ahmedlone127/2023-06-22-icd9_resolver_pipeline_en.md, docs/_posts/murat-gunay/2020-09-01-posology_re.md
Example sentences have been changed and their results have been corrected.
Typos corrections were made.
=> updated md card

docs/en/benchmark.md
NER 
NER+resolver timiong added
=> emr benchmark

docs/_includes/docs-healthcare-pagination.html, docs/en/licensed_version_compatibility.md, docs/en/spark_nlp_healthcare_versions/licensed_release_notes.md, docs/en/spark_nlp_healthcare_versions/release_notes_5_3_0.md
added new release notes to webpage
and updated pagination and compatibility table
=> New Healthcare Release

docs/en/chatbot/releases/Release_notes.md
- Minor changes to the text
- Added the description regarding Follow-up Suggestions only being shown for responses generated from MedResearch
- Added Gifs and Screenshots
=> Update Release_notes.md + Gifs added (0.2.0)

docs/_posts/akrztrk/2024-03-14-icd10_meddra_llt_mapper_en.md, docs/_posts/akrztrk/2024-03-14-meddra_llt_icd10_mapper_en.md
=> updated md

docs/en/benchmark.md
DEID pretrained pipelines (base vs optimized) cost benchmarks added [AWS EMR ~ AWS EC2 Instance ~ DataBricks]
=> DEID pretrained pipelines cost benchmarks added2

docs/en/licensed_annotator_entries/AssertionMerger.md, docs/en/licensed_annotator_entries/EntityRulerInternal.md, docs/en/licensed_annotator_entries/Flattener.md, docs/en/licensed_annotator_entries/RegexMatcherInternal.md, docs/en/licensed_annotator_entries/TextMatcherInternal.md, docs/en/licensed_annotators.md
Annotators have been updated according to the latest 5.3.1 release.
=> updated annatators

docs/en/benchmark.md
=> Databricks  deid pipelines cost benchmarks added

docs/en/annotators.md, docs/en/licensed_annotator_entries/FewShotAssertionClassifierModel.md, docs/en/licensed_annotators.md
FewShotAssertionClassifierModel . md file added.
=> updated md file

docs/en/benchmark.md
added 10 different pipeline timing cost
=> added deid pipeline benchmarks

docs/en/licensed_annotator_entries/LightDeidentification.md
LightDeidentification .md is updated.
=> updated .md file

docs/en/licensed_install.md
added guideline for apple-silicon support
=> added apple silicon installation

docs/en/annotators.md, docs/en/licensed_annotator_entries/GenericRE.md, docs/en/licensed_annotator_entries/PosologyRE.md
PosologyREModel and GenericREModel .md files added.
Issue -> [#2312](https://github.com/JohnSnowLabs/spark-nlp-internal/issues/2312)
=> added posology/generic .md files.

docs/en/chatbot/releases/Release_notes.md
=> Update Release_notes.md + updated 0.3.0 

docs/_data/navigation.yml, docs/en/licensed_install.md
changed installation navigation 
updated Healthcare emphasize
=> webpage update

johnsnowlabs/auto_install/databricks/install_utils.py, johnsnowlabs/settings.py, johnsnowlabs/utils/env_utils.py
Fix `is_running_in_databricks` function
=> Fix is_running_in_databricks function

docs/en/jsl/jsl_release_notes.md, johnsnowlabs/auto_install/databricks/install_utils.py, johnsnowlabs/settings.py, johnsnowlabs/utils/env_utils.py
Fix Detection of Databricks environment https://github.com/JohnSnowLabs/johnsnowlabs/pull/1222 and follow up bugs in Endpoint Environments
=> Fix is_running_in_databricks function (#1222)

docs/en/licensed_annotator_entries/AssertionDL.md, docs/en/licensed_annotator_entries/DeIdentification.md, docs/en/licensed_annotator_entries/GenericClassifier.md, docs/en/licensed_annotator_entries/RENerChunksFilter.md, docs/en/licensed_annotator_entries/RelationExtraction.md
Updated healthcare documentation for v5.3.3 release
=> Updated healthcare documentation for v5.3.3 release

docs/_posts/Cabir40/2024-07-12-jsl_medm_q16_v1_en.md, docs/_posts/Cabir40/2024-07-12-jsl_medm_q4_v1_en.md, docs/_posts/Cabir40/2024-07-12-jsl_medm_q8_v1_en.md, docs/_posts/Cabir40/2024-07-12-jsl_medner_zs_q16_en.md, docs/_posts/Cabir40/2024-07-12-jsl_medner_zs_q4_en.md, docs/_posts/Cabir40/2024-07-12-jsl_medner_zs_q8_en.md, docs/_posts/Cabir40/2024-07-12-jsl_meds_q18_v1_en.md, docs/_posts/Cabir40/2024-07-12-jsl_meds_q4_v1_en.md, docs/_posts/Cabir40/2024-07-12-jsl_meds_q8_v1_en.md, docs/en/spark_nlp_healthcare_versions/licensed_release_notes.md, docs/en/spark_nlp_healthcare_versions/release_notes_5_4_0.md
added LLM model table into RN
fixed model card date
fixed typos
=> web page update

docs/_posts/gokhanturer/2024-03-27-clinical_deidentification_multi_mode_output_en.md
This PR updates the deploy section in docs/_posts/gokhanturer/2024-03-27-clinical_deidentification_multi_mode_output_en.md with the latest links.
=> Update deploy section for en.de_identify.clinical_deidentification_multi_mode_output

docs/_posts/C-K-Loan/2023-06-17-clinical_deidentification_it.md, docs/_posts/ahmedlone127/2023-06-22-clinical_deidentification_ar.md, docs/_posts/ahmet-mesut/2023-09-09-ner_sdoh_langtest_pipeline_en.md, docs/_posts/bugeki/2024-05-07-explain_clinical_doc_granular_en.md, docs/_posts/josejuanmartinez/2022-06-21-clinical_deidentification_pt_3_0.md
This PR updates the deploy sections of posts with the latest links.
=> Update Endpoints Info

docs/_posts/Ahmetemintek/2022-07-26-umls_clinical_findings_resolver_pipeline_en_3_0.md, docs/_posts/Ahmetemintek/2022-07-26-umls_drug_resolver_pipeline_en_3_0.md, docs/_posts/C-K-Loan/2023-06-17-icd10_icd9_mapping_en.md, docs/_posts/C-K-Loan/2023-06-17-icd10cm_umls_mapping_en.md, docs/_posts/C-K-Loan/2023-06-17-mesh_umls_mapping_en.md, docs/_posts/C-K-Loan/2023-06-17-ner_nihss_pipeline_en.md, docs/_posts/C-K-Loan/2023-06-17-ner_pathogen_pipeline_en.md, docs/_posts/C-K-Loan/2023-06-17-rxnorm_mesh_mapping_en.md, docs/_posts/C-K-Loan/2023-06-17-rxnorm_ndc_mapping_en.md, docs/_posts/C-K-Loan/2023-06-17-rxnorm_umls_mapping_en.md, docs/_posts/C-K-Loan/2023-06-17-snomed_icd10cm_mapping_en.md, docs/_posts/C-K-Loan/2023-06-17-snomed_umls_mapping_en.md, docs/_posts/Cabir40/2023-06-17-ner_living_species_pipeline_en.md, docs/_posts/Damla-Gurbaz/2022-06-27-snomed_icdo_mapping_en_3_0.md, docs/_posts/Meryem1425/2022-06-06-sbiobertresolve_icdo_augmented_en_3_0.md, docs/_posts/ahmedlone127/2023-06-16-ner_anatomy_pipeline_en.md, docs/_posts/ahmedlone127/2023-06-21-bert_sequence_classifier_vop_hcp_consult_pipeline_en.md, docs/_posts/ahmedlone127/2023-06-22-icd10cm_resolver_pipeline_en.md, docs/_posts/ahmedlone127/2023-06-22-icd9_resolver_pipeline_en.md, docs/_posts/ahmet-mesut/2023-08-01-sbiobertresolve_loinc_augmented_en.md, docs/_posts/akrztrk/2024-01-18-hpo_resolver_pipeline_en.md, docs/_posts/akrztrk/2024-01-26-sbiobertresolve_snomed_findings_en.md, docs/_posts/gokhanturer/2024-03-20-medication_resolver_pipeline_en.md
This PR updates the deploy sections of posts with the latest links.
=> Update Endpoints Info for Databricks models

docs/_posts/gokhanturer/2024-08-12-large_fewshot_classifier_ade_en.md
large_fewshot_classifier_ade model was trained
=> 2024-08-12-large_fewshot_classifier_ade_en

docs/_posts/gokhanturer/2024-03-27-clinical_deidentification_multi_mode_output_en.md
This PR updates the deploy sections of posts with the latest links.
=> Add Snowflake API Endpoint for Clinical Deid Model

docs/_posts/gokhanturer/2024-08-21-jsl_medm_q16_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_medm_q18_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_medm_q4_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_meds_ner_q16_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_meds_ner_q4_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_meds_ner_q8_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_meds_rag_q16_v1_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_meds_rag_q4_v1_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_meds_rag_q8_v1_en.md
`jsl_meds_ner_q16_v2`, ` jsl_meds_ner_q8_v2`, `jsl_meds_ner_q4_v2`,  `jsl_medm_q16_v2`, `jsl_medm_q4_v2`
=> Created md cars for the LLM models

docs/_posts/gokhanturer/2024-08-21-jsl_medm_q16_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_medm_q4_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_medm_q8_v2_en.md
Fixed typos, and model versions
=> Mgt llm md card 21 08

docs/_posts/bugeki/2024-08-22-icd10cm_resolver_pipeline_en.md, docs/_posts/bugeki/2024-08-22-icd10cm_rxnorm_resolver_pipeline_en.md, docs/_posts/bugeki/2024-08-22-medication_resolver_pipeline_en.md, docs/_posts/bugeki/2024-08-22-medication_resolver_transform_pipeline_en.md, docs/_posts/bugeki/2024-08-22-rxnorm_resolver_pipeline_en.md, docs/_posts/bugeki/2024-08-22-sbiobertresolve_icd10cm_augmented_billable_hcc_en.md, docs/_posts/bugeki/2024-08-22-sbiobertresolve_icd10cm_augmented_en.md, docs/_posts/bugeki/2024-08-22-sbiobertresolve_icd10cm_slim_normalized_en.md
Upload models with version 3.0;
sbiobertresolve_icd10cm_augmented
sbiobertresolve_icd10cm_augmented_billable_hcc
sbiobertresolve_icd10cm_slim_normalized
=> 2024-08-22-sbiobertresolve_icd10cm_augmented_billable_hcc_en

docs/_posts/Ahmetemintek/2022-09-30-icd9_resolver_pipeline_en.md, docs/_posts/C-K-Loan/2023-06-22-icd9_resolver_pipeline_en.md, docs/_posts/Cabir40/2023-03-29-icd9_resolver_pipeline_en.md, docs/_posts/Cabir40/2023-06-22-icd9_resolver_pipeline_en.md, docs/_posts/ahmedlone127/2023-06-22-icd9_resolver_pipeline_en.md, docs/_posts/akrztrk/2024-08-02-bert_sequence_classifier_metastasis_en.md, docs/_posts/akrztrk/2024-08-20-ner_stigmatization_wip_en.md, docs/en/spark_nlp_healthcare_versions/licensed_release_notes.md, docs/en/spark_nlp_healthcare_versions/release_notes_5_4_1.md
- Fixed the broken links on Release Notes
-  Updated icd9_resolver_pipeline cards with predicted entities
=> Fixed the broken links

docs/_posts/gokhanturer/2024-09-06-ner_deid_generic_docwise_en.md, docs/_posts/gokhanturer/2024-09-06-ner_deid_subentity_augmented_docwise_en.md, docs/_posts/gokhanturer/2024-09-06-ner_deid_subentity_docwise_en.md
`ner_deid_generic_docwise`
`ner_deid_subentity_docwise`
`ner_deid_subentity_augmented_docwise`  models were uploaded.
=> 2024-09-06-ner_deid_generic_docwise_en

docs/_posts/gokhanturer/2024-09-09-country_matcher_en.md, docs/_posts/gokhanturer/2024-09-09-state_matcher_en.md, docs/_posts/gokhanturer/2024-09-09-zip_parser_en.md
PR for:
- `country_matcher`,
- `zip_parser`,
- `state_matcher`
=> 2024-09-09-country_matcher_en

docs/_posts/Cabir40/2023-03-13-ner_deid_subentity_augmented_pipeline_en.md, docs/_posts/gokhanturer/2024-09-09-country_matcher_en.md, docs/_posts/murat-gunay/2022-03-21-ner_deid_subentity_augmented_pipeline_en_3_0.md
`ner_deid_subentity_augmented_pipeline`
=> ner_deid_subentity_augmented_pipeline

docs/_posts/aymanechilah/2023-01-03-ner_deid_large_en_3_2.md, docs/_posts/aymanechilah/2023-01-10-general_model_table_detection_v2_en_3_2.md, docs/_posts/aymanechilah/2023-01-10-image_text_detector_v2_en_3_2.md, docs/_posts/aymanechilah/2023-01-10-text_cleaner_v1_en_3_2.md, docs/_posts/aymanechilah/2023-01-17-docvqa_donut_base_en_3_2.md, docs/_posts/aymanechilah/2023-01-17-docvqa_donut_base_opt_en_3_2.md, docs/_posts/aymanechilah/2023-07-11-dit_base_finetuned_rvlcdip_en_3_2.md, docs/_posts/aymanechilah/2023-07-11-tabform_v1_en_3_2.md, docs/_posts/aymanechilah/2023-09-14-lilt_roberta_funsd_v1_en_3_2.md, docs/_posts/aymanechilah/2023-09-14-lilt_rvl_cdip_296K_en_3_2.md, docs/_posts/aymanechilah/2023-09-27-image_text_detector_dit_en_3_2.md, docs/_posts/aymanechilah/2023-11-20-docvqa_pix2struct_en_3_2.md, docs/_posts/aymanechilah/2023-11-20-publaynet_dit_base_mrcnn_en_3_2.md, docs/_posts/aymanechilah/2024-03-15-docvqa_pix2struct_jsl_opt_en_3_2.md, docs/_posts/aymanechilah/2024-03-15-image_handwritten_detector_jsl_en_3_2.md, docs/_posts/aymanechilah/2024-03-15-region_cell_detection_en_3_2.md, docs/_posts/aymanechilah/2024-03-15-region_cell_detection_v2_en_3_2.md, docs/_posts/aymanechilah/2024-03-15-table_detection_v3_en_3_2.md, docs/_posts/aymanechilah/2024-04-15-chart_to_text_deplot_jsl_en_3_2.md, docs/_posts/aymanechilah/2024-04-15-checkbox_detector_v1_en_3_2.md, docs/_posts/aymanechilah/2024-04-15-info_docvqa_pix2struct_jsl_base_opt_en_3_2.md, docs/_posts/aymanechilah/2024-09-30-visual_re_geo_v1_en_3_2.md, docs/_posts/aymanechilah/2024-09-30-visual_re_geo_v2_en_3_2.md
Update predicted entities in ocr cards
=> Update entities 

docs/_includes/docs-annotation-pagination.html, docs/en/alab/annotation_labs_releases/release_notes_6_8_1.md, docs/en/alab/release_notes.md
6.8.1 release notes for website
=> 6.8.1 release notes for website

docs/en/jsl/jsl_release_notes.md, docs/en/jsl/snowflake_utils.md, johnsnowlabs/auto_install/docker/work_utils.py, johnsnowlabs/auto_install/snowflake/work_utils.py, johnsnowlabs/finance.py, johnsnowlabs/legal.py, johnsnowlabs/medical.py, johnsnowlabs/settings.py, johnsnowlabs/utils/py_process.py, notebooks/create_snowflake_endpoint.ipynb
- bump spark-nlp to 551
- bump spark-nlp-jsl to 551
- Support new spark-nlp-jsl annotators:
-     ContextualEntityRuler,  PretrainedZeroShotNER, StructuredJsonConverter
Note: change base branch
=> spark-nlp-jsl==5.5.1 compatibility

docs/en/benchmark.md, docs/en/benchmark_llm.md
Added ZeroShot Deidentification Pipelines Speed Comparison
=> upload new benchmark table

docs/_posts/akrztrk/2024-10-01-jsl_medm_q8_v1_en.md, docs/_posts/akrztrk/2024-10-01-jsl_meds_ner_q4_v2_en.md, docs/_posts/akrztrk/2024-10-04-jsl_medm_q4_v1_en.md, docs/_posts/akrztrk/2024-10-04-jsl_meds_ner_q16_v2_en.md, docs/_posts/akrztrk/2024-10-04-jsl_meds_ner_q8_v2_en.md, docs/_posts/akrztrk/2024-10-04-jsl_meds_ner_zs_q16_v1_en.md, docs/_posts/akrztrk/2024-10-04-jsl_meds_ner_zs_q4_v1_en.md, docs/_posts/akrztrk/2024-10-04-jsl_meds_ner_zs_q8_v1_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q16_v1_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q16_v2_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q16_v3_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q4_v1_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q4_v2_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q4_v3_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q8_v1_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q8_v2_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_q8_v3_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_rag_q16_v1_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_rag_q4_v1_en.md, docs/_posts/akrztrk/2024-10-05-jsl_meds_rag_q8_v1_en.md, docs/_posts/akrztrk/2024-10-06-jsl_medm_q4_v2_en.md, docs/_posts/akrztrk/2024-10-06-jsl_medm_q4_v3_en.md, docs/_posts/akrztrk/2024-10-06-jsl_medm_q8_v2_en.md, docs/_posts/akrztrk/2024-10-08-jsl_medm_q16_v2_en.md, docs/_posts/akrztrk/2024-10-08-jsl_medm_q8_v3_en.md, docs/_posts/akrztrk/2024-10-15-jsl_medm_q16_v1_en.md
=> added info

docs/en/licensed_annotator_entries/AssertionDL.md, docs/en/licensed_annotator_entries/BertSentenceChunkEmbeddings.md, docs/en/licensed_annotator_entries/ContextualEntityFilterer.md, docs/en/licensed_annotator_entries/ContextualEntityRuler.md, docs/en/licensed_annotator_entries/DeIdentification.md, docs/en/licensed_annotator_entries/FewShotAssertionClassifier.md
Addition healthcare docs to Annotator page for v552
=> Addition healthcare docs to Annotator page for v552

docs/_includes/docs-annotation-pagination.html, docs/en/alab/annotation_labs_releases/release_notes_6_10_1.md, docs/en/alab/release_notes.md
=> 6.10.1 release notes

docs/en/alab/annotation_labs_releases/release_notes_6_8_0.md, docs/en/alab/annotation_labs_releases/release_notes_6_8_1.md
=> Fix docs in 680 release notes

docs/_posts/gokhanturer/2025-02-19-sbiobertresolve_mesh_augmented_en.md, docs/_posts/gokhanturer/2025-02-19-sbiobertresolve_mesh_en.md, docs/_posts/gokhanturer/2025-02-19-sbiobertresolve_mesh_veterinary_en.md
- `sbiobertresolve_mesh_augmented`
- `sbiobertresolve_mesh_veterinary`
- `sbiobertresolve_mesh` models were uploaded
=> 2025-02-19-sbiobertresolve_mesh_augmented_en

docs/_posts/aymanechilah/2025-02-19-dicom_deid_full_anonymization_en_3_4.md, docs/_posts/aymanechilah/2025-02-19-dicom_deid_generic_augmented_minimal_en_3_4.md, docs/_posts/aymanechilah/2025-02-19-dicom_deid_generic_augmented_pseudonym_en_3_4.md
=> fix issues dicom

docs/en/licensed_annotator_entries/ContextualEntityRuler.md, docs/en/licensed_annotator_entries/StructuredJsonConverter.md, docs/en/utility_helper_modules.md
- CER features
- Structured Deid changes
- StructuredJsonConverter new features
=> 553 documentation update

docs/_includes/docs-annotation-pagination.html, docs/en/alab/annotation_labs_releases/release_notes_6_11_1.md, docs/en/alab/release_notes.md
=> 6.11.1 release notes

docs/_posts/aymanechilah/2023-01-10-text_cleaner_v1_en_3_2.md, docs/_posts/aymanechilah/2023-01-10-visualner_10kfilings_en_3_2.md, docs/_posts/aymanechilah/2023-01-10-visualner_keyvalue_10kfilings_en_3_2.md, docs/_posts/aymanechilah/2023-07-11-tabform_v1_en_3_2.md, docs/_posts/aymanechilah/2023-08-22-visualclf_vit_dicom_en.md, docs/_posts/aymanechilah/2023-11-06-image_handwritten_transformer_extraction_en_3_2.md, docs/_posts/aymanechilah/2023-11-06-mixed_scanned_digital_pdf_en_3_2.md, docs/_posts/aymanechilah/2023-11-06-mixed_scanned_digital_pdf_skew_correction_en_3_2.md, docs/_posts/aymanechilah/2023-11-15-image_printed_transformer_extraction_en_3_2.md, docs/_posts/aymanechilah/2023-11-15-mixed_scanned_digital_pdf_image_cleaner_en_3_2.md, docs/_posts/aymanechilah/2023-11-15-pdf_handwritten_transformer_extraction_en_3_2.md, docs/_posts/aymanechilah/2023-11-15-pdf_printed_transformer_extraction_en_3_2.md, docs/_posts/aymanechilah/2024-09-30-basic_table_extractor_en_3_2.md, docs/_posts/aymanechilah/2024-09-30-digital_pdf_table_extractor_en_3_2.md, docs/_posts/aymanechilah/2025-02-19-dicom_deid_full_anonymization_en_3_4.md, docs/_posts/aymanechilah/2025-02-19-dicom_deid_generic_augmented_pseudonym_en_3_4.md
Modified ocr cards descriptions
=> update cards description

docs/_posts/Meryem1425/2025-03-18-clinical_deidentification_docwise_wip_en.md
=> 2025-03-18-clinical_deidentification_docwise_wip_en

docs/_posts/Cabir40/2024-07-12-jsl_medm_q16_v1_en.md, docs/_posts/Cabir40/2024-07-12-jsl_medm_q4_v1_en.md, docs/_posts/Cabir40/2024-07-12-jsl_medm_q8_v1_en.md, docs/_posts/akrztrk/2024-10-01-jsl_medm_q8_v1_en.md, docs/_posts/akrztrk/2024-10-04-jsl_medm_q4_v1_en.md, docs/_posts/akrztrk/2024-10-06-jsl_medm_q4_v2_en.md, docs/_posts/akrztrk/2024-10-06-jsl_medm_q4_v3_en.md, docs/_posts/akrztrk/2024-10-06-jsl_medm_q8_v2_en.md, docs/_posts/akrztrk/2024-10-08-jsl_medm_q16_v2_en.md, docs/_posts/akrztrk/2024-10-08-jsl_medm_q8_v3_en.md, docs/_posts/akrztrk/2024-10-15-jsl_medm_q16_v1_en.md, docs/_posts/akrztrk/2024-10-23-jsl_medm_q16_v3_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_medm_q16_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_medm_q4_v2_en.md, docs/_posts/gokhanturer/2024-08-21-jsl_medm_q8_v2_en.md
add this explanation to our jsl_medm_xx model description
NOTE: "This model's size is 8B and is available to Healthcare NLP license owners for free. However, this is not the most capable medical LLM that John Snow has to Labs offer. For the larger and better versions, please try out the models we have in [marketplaces](https://aws.amazon.com/marketplace/pp/prodview-z4jqmczvwgtby)."
=> added note into description part

docs/en/chatbot/releases/Release_notes.md
- added section for MDPI KB integration
=> Update Release_notes.md (MDPI)

docs/_posts/Meryem1425/2025-04-09-clinical_deidentification_docwise_benchmark_en.md
=> 2025-04-09-clinical_deidentification_docwise_benchmark_en

docs/en/licensed_annotator_entries/AnnotationConverter.md, docs/en/licensed_annotator_entries/BertForAssertionClassification.md, docs/en/licensed_annotator_entries/ContextualEntityRuler.md, docs/en/licensed_annotator_entries/DeIdentification.md, docs/en/licensed_annotator_entries/FhirDeIdentification.md, docs/en/licensed_annotator_entries/LightDeidentification.md, docs/en/licensed_annotators.md, docs/en/utility_helper_modules.md
1- BertForAssertionClassification
2- FhirDeidentification
3- Annotation Converter 
4- Deidentification params -> groupBy, consistentAcrossNameParts, chunkMatching
=> release 6.0.0 web doc

docs/en/licensed_annotator_entries/AnnotationConverter.md, docs/en/licensed_annotator_entries/BertForAssertionClassification.md, docs/en/licensed_annotator_entries/FhirDeIdentification.md
=> release 6.0.0 update 2

docs/_posts/nogifeet/2025-05-09-pdf_deid_multi_model_context_pipeline.md, docs/_posts/nogifeet/2025-05-09-pdf_obfuscation_multi_model_context_pipeline.md
Added Documentation For PDF Pretrained Pipelines 
pdf_deid_multi_model_context_pipeline
pdf_obfuscation_multi_model_context_pipeline
=> Added Documentation For PDF Deid/Obfuscation

docs/en/licensed_annotator_entries/DeIdentification.md, docs/en/licensed_annotator_entries/LightDeidentification.md, docs/en/utility_helper_modules.md
=> release 603 web doc update

docs/en/licensed_annotator_entries/LightDeidentification.md, docs/en/utility_helper_modules.md
=> web page 603 update 2 

docs/demos/medical_files.md, docs/demos/visual_document_understanding.md
=> update demo page

docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_4b_q16_v4_en.md, docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_4b_q16_v5_en.md, docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_4b_q4_v4_en.md, docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_4b_q4_v5_en.md, docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_4b_q8_v4_en.md, docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_4b_q8_v5_en.md, docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_8b_q16_v4_en.md, docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_8b_q4_v4_en.md, docs/_posts/AbdullahMubeenAnwar/2025-08-05-jsl_meds_8b_q8_v4_en.md
=> 2025-08-05-jsl_meds_8b_q16_v4_en

docs/_posts/Meryem1425/2025-02-28-biolordresolve_icd10gm_augmented_de.md, docs/_posts/gokhanturer/2025-02-19-sbiobertresolve_mesh_augmented_en.md, docs/_posts/gokhanturer/2025-02-19-sbiobertresolve_mesh_veterinary_en.md
I have updated the following models card with the colab link:
- [sbiobertresolve_mesh_augmented](https://nlp.johnsnowlabs.com/2025/02/19/sbiobertresolve_mesh_augmented_en.html)
- [sbiobertresolve_mesh_veterinary](https://nlp.johnsnowlabs.com/2025/02/19/sbiobertresolve_mesh_veterinary_en.html)
- [biolordresolve_icd10gm_augmented](https://nlp.johnsnowlabs.com/2025/02/28/biolordresolve_icd10gm_augmented_de.html)
=> Added colab link
